extern const int long_size;
extern const int int_size;
extern int verbose;
extern int target_pid;
unsigned long long target_offset;
extern int *numbers;
extern unsigned long currnum;
extern int quit;
extern unsigned long num_numbers;
extern int monmode;
